# YAML config file for generating a BSgenome and TxDb object
# The config file is read by R command line script construct_BSgenome_package.R
#
# Note: Most entries are critical, so deleting/removing entries will break
# the script. Only change entries if you know what you are doing.
#
# Author: Maurits Evers (maurits.evers@anu.edu.au)


# Sequence parameters
seq:
    chr: c(1:22, "X", "Y", "MT")
    chr_circ: c("MT", "U13369.1")


# Ensembl download parameters
download:
    baseurl_ensembl: ftp://ftp.ensembl.org/pub/release-89


# Parameters for BSgenome
BSgenome:
    Package: BSgenome.Hsapiens.mevers.hs1
    Title: Chromosome plus MT plus rDNA sequences for Homo sapiens (based on Ensembl GRCh38)
    Description: Hard-masked chromosome (1-22, X, Y) plus MT plus rDNA (GenBank U13369.1) sequences for Homo sapiens (based on Ensembl GRCh38)
    Version: 1.0.0
    Author: Ensembl+NCBI
    Maintainer: Maurits Evers <maurits.evers@anu.edu.au>
    License: GPL (>= 2)
    organism: Homo sapiens
    common_name: Human
    provider: Ensembl+NCBI
    provider_version: hs1
    release_date: Mar. 2018
    release_name: Human masked chromosome plus MT plus rDNA sequences
    organism_biocview: Homo_sapiens
    BSgenomeObjname: HSapiens
#    seqnames: c(seq(1:22), "X", "Y", "MT", "U13369.1")
#    circ_seqs: c("MT", "U13369.1")
#    seqnames: c(paste0("chr", seq(1:22)), "chrX", "chrY", "chrM", "U13369.1")
#    circ_seqs: c("chrM", "U13369.1")
    seqfiles_suffix: .fa.gz
